/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.politecnicomalaga.ejercicio_bucle_1;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        
        Scanner miScan = new Scanner(System.in);
        
        System.out.println("Introduzca un número: ");
        int num = miScan.nextInt();
        
        for(int i = 0;i < 10;i++){
            
            int multiplos = num * i;
            System.out.println("El " + (i + 1) + "º múltiplo del número introducido es: " + multiplos);

        }
        
    }
}